### ISSUE TITLE
DocSynth-300K

### ISSUE THREAD

**Issue by Mushroomcat9998** [JulioZhao97/pretrain_layout#1]
Thank you and your partner so much for your publication about DocLayout-YOLO.
I'd like to know if this repo generates the DocSynth-300K dataset. Is it private for outsiders? If not, can you please share the DocSynth-300K dataset? I intend to use it for my research on layout segmentation.
Have a nice day!

**Comment by JulioZhao97** [comment]
Yes, the DocSynth-300K dataset and data generation code will be made public available soon, please follow  [DocLayout-YOLO](https://github.com/opendatalab/DocLayout-YOLO) for further update.
